name: run unit tests of feature branch

on:
  push:
    branches:
      'feature/*'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: run unit test
        run: mvn test
    

  
